/*
Endpoints

Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AuthenticationApi,
  CompanyApi,
  DepartmentsApi,
  EngagementsApi,
  ExpensesApi,
  OperationsApi,
  PayrollApi,
  TimeOffApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { OysterCustom } from "./client-custom";

export class Oyster extends OysterCustom {
  readonly authentication: AuthenticationApi;
  readonly company: CompanyApi;
  readonly departments: DepartmentsApi;
  readonly engagements: EngagementsApi;
  readonly expenses: ExpensesApi;
  readonly operations: OperationsApi;
  readonly payroll: PayrollApi;
  readonly timeOff: TimeOffApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.authentication = new AuthenticationApi(configuration);
    this.company = new CompanyApi(configuration);
    this.departments = new DepartmentsApi(configuration);
    this.engagements = new EngagementsApi(configuration);
    this.expenses = new ExpensesApi(configuration);
    this.operations = new OperationsApi(configuration);
    this.payroll = new PayrollApi(configuration);
    this.timeOff = new TimeOffApi(configuration);
  }

}
