/*
Endpoints

Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AuthenticationCreateAccessTokenRequest
 */
export interface AuthenticationCreateAccessTokenRequest {
    /**
     * The client_id of your Developer App. This can be found by visting https://app.oysterhr.com/developer
     * @type {string}
     * @memberof AuthenticationCreateAccessTokenRequest
     */
    'client_id'?: string;
    /**
     * The secret of your Developer App.
     * @type {string}
     * @memberof AuthenticationCreateAccessTokenRequest
     */
    'client_secret'?: string;
    /**
     * First you need to request an `authorization_code`. Afterwards you can request a `refresh_token`.
     * @type {string}
     * @memberof AuthenticationCreateAccessTokenRequest
     */
    'grant_type'?: string;
    /**
     * The code is required when requesting an `authorization_code`.
     * @type {string}
     * @memberof AuthenticationCreateAccessTokenRequest
     */
    'code'?: string;
    /**
     * The redirect_uri is required when requesting an `authorization_code`.
     * @type {string}
     * @memberof AuthenticationCreateAccessTokenRequest
     */
    'redirect_uri'?: string;
    /**
     * A `refresh_token` is required when requesting a `refresh_token`. A `refresh_token` will be provided when requesting an `authorization_code`
     * @type {string}
     * @memberof AuthenticationCreateAccessTokenRequest
     */
    'refresh_token'?: string;
}

