/*
Endpoints

Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EngagementBenefitEnrollmentsInner } from './engagement-benefit-enrollments-inner';
import { EngagementDepartment } from './engagement-department';
import { EngagementPersonalDetails } from './engagement-personal-details';
import { EngagementTerminationsInner } from './engagement-terminations-inner';

/**
 * 
 * @export
 * @interface Engagement
 */
export interface Engagement {
    /**
     * 
     * @type {string}
     * @memberof Engagement
     */
    'engagementId': string;
    /**
     * 
     * @type {string}
     * @memberof Engagement
     */
    'modifiedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Engagement
     */
    'startDate': string;
    /**
     * 
     * @type {string}
     * @memberof Engagement
     */
    'engagementType': EngagementEngagementTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Engagement
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof Engagement
     */
    'role': string;
    /**
     * 
     * @type {string}
     * @memberof Engagement
     */
    'countryCode': string;
    /**
     * 
     * @type {EngagementPersonalDetails}
     * @memberof Engagement
     */
    'personalDetails': EngagementPersonalDetails;
    /**
     * 
     * @type {object}
     * @memberof Engagement
     */
    'employment'?: object | null;
    /**
     * 
     * @type {object}
     * @memberof Engagement
     */
    'contract'?: object | null;
    /**
     * 
     * @type {Array<EngagementBenefitEnrollmentsInner>}
     * @memberof Engagement
     */
    'benefitEnrollments'?: Array<EngagementBenefitEnrollmentsInner>;
    /**
     * 
     * @type {Array<EngagementTerminationsInner>}
     * @memberof Engagement
     */
    'terminations'?: Array<EngagementTerminationsInner>;
    /**
     * 
     * @type {EngagementDepartment}
     * @memberof Engagement
     */
    'department'?: EngagementDepartment | null;
}

type EngagementEngagementTypeEnum = 'EMPLOYMENT' | 'CONTRACT'


