/*
Endpoints

Oyster uses OAuth2 to enable customers to grant access to their data to third party applications. Customers also need to use this API to authenticate themselves when making API requests.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Meta } from './meta';
import { Payroll } from './payroll';

/**
 * 
 * @export
 * @interface PayrollGetAllPayrollsResponse
 */
export interface PayrollGetAllPayrollsResponse {
    /**
     * 
     * @type {Array<Payroll>}
     * @memberof PayrollGetAllPayrollsResponse
     */
    'data': Array<Payroll>;
    /**
     * 
     * @type {Meta}
     * @memberof PayrollGetAllPayrollsResponse
     */
    'meta': Meta;
}

